### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by liangtingStduy** [RomaSo/dbus_gatt#2]
Do you support arm。
issue:
CMakeFiles/example_dbus_gatt.dir/main.cpp.o: In function `std::__exception_ptr::exception_ptr std::make_exception_ptr<std::future_error>(std::future_error)':
main.cpp:(.text._ZSt18make_exception_ptrISt12future_errorENSt15__exception_ptr13exception_ptrET_[_ZSt18make_exception_ptrISt12future_errorENSt15__exception_ptr13exception_ptrET_]+0x34): undefined reference to `__cxa_init_primary_exception'
main.cpp:(.text._ZSt18make_exception_ptrISt12future_errorENSt15__exception_ptr13exception_ptrET_[_ZSt18make_exception_ptrISt12future_errorENSt15__exception_ptr13exception_ptrET_]+0x58): undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)'
collect2: error: ld returned 1 exit status
example/CMakeFiles/example_dbus_gatt.dir/build.make:108: recipe for target 'example/example_dbus_gatt' failed
make[2]: *** [example/example_dbus_gatt] Error 1
CMakeFiles/Makefile2:140: recipe for target 'example/CMakeFiles/example_dbus_gatt.dir/all' failed
make[1]: *** [example/CMakeFiles/example_dbus_gatt.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by RomaSo** [comment]
Hi Ethan. Yes, this library works well on ARM cortex A53

**Comment by RomaSo** [comment]
This error looks like something wrong with std library or compiler

**Comment by liangtingStduy** [comment]
This is an automatic reply,confirming that your e-mail was received.Thank you!-------------------------------------liangting
