### ISSUE TITLE
How can I Advertise on BLE with dbus_gatt?

### ISSUE THREAD

**Issue by schneeweiss2** [RomaSo/dbus_gatt#3]
How can I Advertise BLE? Is it missing?

**Comment by RomaSo** [comment]
BLE device management is not a part of this library. Bluez also does not support BLE device management via dbus 
To managment BLE device you can use btmgmt and hciconfig
Example:
btmgmt -i 0 power off
hciconfig 0 reset
btmgmt -i 0 bredr off
btmgmt -i 0 le on
btmgmt -i 0 connectable on
btmgmt -i 0 advertising on
btmgmt -i 0 power on
